blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    # blog:index: list all posts
    path('', views.PostListView.as_view(), name='index'),

    # blog:post-detail: post's detail
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),

    # blog:post-create: create a post
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),

    # blog:post-update: update a post
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(),
        name='post-update'),

    # blog:post-delete: delete a post
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(),
        name='post-delete'),

    # blog:user_posts: user's posts
    path('user/<str:username>/', views.UserPostListView.as_view(),
        name='user-posts'),

    # blog:about: about page
    path('about/', views.about, name='about'),

    #
]

blog_corey/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'users'

urlpatterns = [
    # register user
    path('register/', views.register, name='register'),

    # login user
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),

    # logout user
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logout.html'), name='logout'),

    # profile
    path('profile/', views.profile, name='profile'),

    # password reset
    path('password-reset/', auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html',
            success_url=reverse_lazy('users:password_reset_done')),
        name='password_reset'),

    # password reset done
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'),

    # password reset confirm
    path('password_reset_confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    DEFAULT_IMAGE = 'default.jpg'
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default=f'profile_pics/{DEFAULT_IMAGE}',
        upload_to='profile_pics')

    def save(self):
        super().save()

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (200, 200)
            img.thumbnail(output_size)
            img.save(self.image.path)


    def __str__(self):
        return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from snowpenguin.django.recaptcha2.fields import ReCaptchaField
from snowpenguin.django.recaptcha2.widgets import ReCaptchaWidget
from snowpenguin.django.recaptcha2.widgets import ReCaptchaHiddenInput
from .models import Profile


class UserRegisterForm(UserCreationForm):
    # firstname = forms.CharField()
    # lastname = forms.CharField()
    email = forms.EmailField()
    # captcha = ReCaptchaField(widget=ReCaptchaHiddenInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        # add  `captcha, firstname, lastname`  fields


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email')


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView
)
from django.contrib.auth.models import User
from .models import Post


# index
class PostListView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


# post's detail
class PostDetailView(DetailView):
    model = Post


# create post
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('title', 'content')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


# update post
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ('title', 'content')

    def test_func(self):
        post = self.get_object()
        # test if users are trying to update their or others posts
        return self.request.user == post.author


# post's deletion
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        # test if users are trying to delete their or others posts
        return self.request.user == post.author


# user's posts
class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


# about
def about(request):
    return render(request, 'blog/about.html', {'title': 'about'})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,
                'Your account has been created! You are now able to log in')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES,
            instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('users:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'users/profile.html', context)

blog/templates/blog/about.html
{% extends "layouts/base.html" %}


{% block content %}

    About Page

{% endblock %}

blog/templates/blog/index.html
{% extends "layouts/base.html" %}


{% block content %}

    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'blog:user-posts' username=post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>

                <h3><a class="article-title" href="{% url 'blog:post-detail' pk=post.pk %}">{{ post.title }}</a></h3>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}

    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "layouts/base.html" %}


{% block content %}

    <div class="content-section">
        <form method="post">
            {% csrf_token %}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>

            <div class="form-group">
                <button type="submit" class="btn btn-outline-danger">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' pk=object.pk %}">Cancel</a>
            </div>
        </form>
    </div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "layouts/base.html" %}


{% block content %}

    <article class="media content-section">
        <img class="rounded-circle article-img"
             src="{{ object.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ object.author }}</a>
                <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>

                {% if user.is_authenticated and object.author == user %}
                    <div class="">
                        <a class="btn btn-secondary btn-sm my-1" href="{% url 'blog:post-update' pk=object.pk %}">Update</a>
                        <a class="btn btn-danger btn-sm my-1" href="{% url 'blog:post-delete' pk=object.pk %}">Dalete</a>
                    </div>
                {% endif %}
            </div>

            <h3 class="article-title mt-3">{{ object.title }}</h3>
            <p class="article-content">{{ object.content }}</p>
        </div>
    </article>

{% endblock %}

blog/templates/blog/post_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% load recaptcha2 %}


{% block recaptcha_head %}
    {% recaptcha_init %}
{% endblock %}


{% block content %}

    <div class="content-section">
        <form method="post">
            {% csrf_token %}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>

                {{ form|crispy }}
            </fieldset>

            <div class="form-group">
                <button type="submit" class="btn btn-outline-info">Post</button>

                <!-- update post -->
                {% if object %}
                    <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' pk=object.pk %}">Back</a>
                {% endif %}

            </div>
        </form>
    </div>

{% endblock %}

blog/templates/blog/user_posts.html
{% extends "layouts/base.html" %}


{% block content %}

    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>

    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>

                <h3><a class="article-title" href="{% url 'blog:post-detail' pk=post.pk %}">{{ post.title }}</a></h3>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}

    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}

{% endblock %}

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>
        {% block title %}
            {% if title %}
                Django Blog - {{ title }}
            {% else %}
                Django Blog
            {% endif %}
        {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    {% block recaptcha_head %}{% endblock %}

</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <!-- <nav class="navbar navbar-expand-md navbar-light bg-light"> -->
            <div class="container">

              <a class="navbar-brand mr-4" href="{% url 'blog:index' %}">Django Blog</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="{% url 'blog:index' %}">Home</a>
                  <a class="nav-item nav-link" href="{% url 'blog:about' %}">About</a>
                  {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'blog:post-create' %}">New Post</a>
                  {% endif %}

                </div>

                    <!-- Navbar-right -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
                            <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
                        {% endif %}
                    </div>
                </div><!-- collapse -->
            </div><!-- container -->
        </nav>
    </header>

    <main role="main" class="container">

        <div class="row">
            <div class="col-md-8">

                <!-- Flash messages -->
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <!-- END: Flash messages -->

                {% block content %}{% endblock %}
            </div>

            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class="text-muted">You can put any information here you'd like.</p>
                    <u class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Annoucements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </u>
                </div>
            </div>
        </div><!-- row -->

    </main><!-- container -->

    <!-- Javascripts -->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

</body>
</html>

users/templates/users/login.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}


{% block content %}

    <div class="content-section">
        <form method="post">
            {% csrf_token %}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>

                {{ form|crispy }}
            </fieldset>

            <div class="form-group">
                <button type="submit" class="btn btn-outline-primary">Login</button>
            </div>
        </form>

        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account <a class="ml-2" href="{% url 'users:register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>

{% endblock %}

users/templates/users/logout.html
{% extends "layouts/base.html" %}


{% block content %}

    <h2>You have been loged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'users:login' %}">Log In Again</a>
        </small>
    </div>

{% endblock %}

users/templates/users/password_reset.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}


{% block content %}

    <div class="content-section">
        <form method="post">
            {% csrf_token %}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>

                {{ form|crispy }}
            </fieldset>

            <div class="form-group">
                <button type="submit" class="btn btn-outline-primary">Request Password Reset</button>
            </div>
        </form>
    </div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% load recaptcha2 %}


{% block content %}

    <div class="content-section">
        <form method="post">
            {% csrf_token %}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>

                {{ form|crispy }}
            </fieldset>

            <div class="form-group">
                <button type="submit" class="btn btn-outline-primary">Reset Password</button>
            </div>
        </form>
    </div>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "layouts/base.html" %}


{% block content %}

    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>

{% endblock %}

users/templates/users/profile.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}


{% block content %}

    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img"
                 src="{{ user.profile.image.url }}" alt="User Profile">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>

            </div>
        </div>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">User Info</legend>

                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>

            <div class="form-group">
                <button type="submit"
                         class="btn btn-outline-primary">Update</button>
            </div>
        </form>

    </div>
{% endblock %}

users/templates/users/register.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% load recaptcha2 %}


{% block recaptcha_head %}
    {% recaptcha_init %}
{% endblock %}


{% block content %}

    <div class="content-section">
        <form method="post">
            {% csrf_token %}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>

                {{ form|crispy }}
            </fieldset>

            <div class="form-group">
                <button type="submit" class="btn btn-outline-primary">Sign Up</button>
            </div>
        </form>

        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'users:login' %}">Sign In</a>
            </small>
        </div>
    </div>

{% endblock %}